- targets:  # url;humanname;routing;switch;module
    - a.st1.ntp.br;a.st1.ntp.br;external;internetbox;icmp
    - 8.8.8.8;google-dns;external;internetbox;icmp
    - 192.168.10.1;onu-fiber;local;onu-fiber;icmp
    - 192.168.0.1;router;local;router;icmp